const jobs = [
  {
    id:"1298371489",
    company: "Google",
    url: "www.google.ca",
    position: "UX Designer",
    location: "Seattle",
    status: "full-time",
    compensation: "45",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
  {
    id:"120398123",
    company: "Amazon",
    position: "UX Designer",
    url:"www.amazon.ca",
    location: "Seattle",
    status: "full-time",
    compensation: "60",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
  {
    id:"12937129",
    company: "Twitter",
    position: "UX Designer",
    url: "www.twitter.com",
    location: "Tacoma",
    status: "full-time",
    compensation: "23",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
  {
    id:"13214234",
    company: "Microsoft",
    position: "UX Designer",
    url:"www.microsoft.ca",
    location: "Tacoma",
    status: "full-time",
    compensation: "45",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
  {
    id:"12341235124",
    company: "JPMorgan",
    position: "UX Designer",
    url: "www.jpMorgan.com",
    location: "Tacoma",
    status: "full-time",
    compensation: "45",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
  {
    id:"1456124361246",
    company: "Square",
    position: "UX Designer",
    url:"www.square.ca",
    location: "Seattle",
    status: "full-time",
    compensation: "55",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
  {
    id:"123642365126",
    company: "lululemon",
    position: "UX Designer",
    url: "www.lululemon.ca",
    location: "Tacoma",
    status: "full-time",
    compensation: "75",
    contact_name: "John Doe",
    description: "A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. A full time role for a UX Signer. ",
  },
];


export default jobs;